easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Products
       - App\Entity\ProductDetails
       - App\Entity\Categories
       - App\Entity\Orders
       - App\Entity\SubCategories
       - App\Entity\Users
       - App\Entity\Payments
